/* Création avec MySQL Workbench de la table + ajout de lignes d'initialisation */
CREATE TABLE test_spring.LISTECOURSES(     
	IDOBJET INTEGER AUTO_INCREMENT PRIMARY KEY,      
	LIBELLE VARCHAR(50) NOT NULL,      
	QUANTITE INTEGER NOT NULL );

INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Banane', 3); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Sucre blanc', 75); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Oeuf', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Levure', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Sel', 1); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Farine', 150); 
INSERT INTO LISTECOURSES(LIBELLE, QUANTITE) VALUES('Beurre', 70);	
